### PR TITLE
Front-end clean code

### PR DESCRIPTION
**Pull request by EcutDavid**
BTW, will definitely remove these ugly merge remote branch commits next time making PR.......

### CODE REVIEW

**Comment by makara** [comment]
doesn't have to be next time; just do a rebase from our branch and a force push to your branch.

**Comment by EcutDavid** [comment]
Make sense, thanks!

**Comment by JuhaS** [comment]
@EcutDavid that's really helpful. Let me know if you have some ideas on breaking down the frontend code to smaller components. Currently we leverage too much JS to compose the UI, might as well use React for that, I just wasn't fluent enough in React when I wrote it.

**Comment by EcutDavid** [comment]
@JuhaS Yep, have some idea, will make it in next PR :)

**Comment by JuhaS** [comment]
Going to review and merge this soon, just upgraded to webpack-2 so may have to do some changes.

**Pull request closed without merging**
