### PR TITLE
upgrade frontend app dependency to node v14+ with a lot of dependencies.

### PR DESCRIPTION
**Pull request by sp3c73r2038**
- use yarn for dependencies management
- update webpack to v5 along with a lot of dev dependencies
- update react to v18
- update babel to v7 and use `@babel/plugin-transform-runtime` instead
- use npm dependencies for `bourbon` v7 and `normalize.css`,
  removed in `client/app/styles/vendor`
- move dependeny of PropTypes to `prop-types` npm package
- replace `react-document-title` with `react-helmet`
- remove `react-hot-reload` as it's now embedded in `react-dev-server`
- simplify dev-server, merge 3000 (express) and 3001 (dev-server) into one dev-server
- update README.md

### CODE REVIEW

**Review by kaleocheng — APPROVED** [review]
I don't have time to test it on my local. but LGTM in general

**Comment by sp3c73r2038** [comment]
maybe I could send it to another branch and merge with the BE PR https://github.com/Wiredcraft/pipelines/pull/123 here. then we have it tested somethere (maybe omni pipelines on in-house-builder?).

**Comment by kaleocheng** [comment]
[omni-builder](https://omni-pipelines.wiredcraft.cn/) seesm a good place to test it

**Comment by sp3c73r2038** [comment]
sure i will try to test it on omni-builder first. let's just leave this PR for now.

**Comment by kaleocheng** [comment]
ppl already start to use this pr, seems no issues. let's merge it to master 
图片

**Comment by sp3c73r2038** [comment]
wait for #125.

**Pull request merged**
