### PR TITLE
Slackbot: Slack slash commands integration

### PR DESCRIPTION
**Pull request by JuhaS**
Instructions in wiki: https://github.com/Wiredcraft/pipelines/wiki/Slackbot-instructions

High level changes:
- Refactor some functions to utils.py form server.js to allow usage outside of server.py
- Move some variables to pipelines/__init__.py to allow usage outside of server.py
- Add ['public_slug']['public_slug'] to pipeline-state file when get triggers is first called (same as wh)
- Add new route for "/api/slackbot/({slug})
- Add a no-op `slackbot` plugin that is just used for configuration.
- Fix a few broken tests
- Simple API level tests for slackbot.

### CODE REVIEW

**Comment by xuqingfeng** [comment]
Can slack bot be limited to some specific users?

**Comment by zbal** [comment]
@xuqingfeng indirectly yes - along with the command, we receive the whole execution context and can apply filter at-posteriori - in pipelines. Not sure about filtering in slack plugin itself @JuhaS ?

**Comment by JuhaS** [comment]
- Moved the slackbot configs to be inside triggers as discussed with @zbal 
- Added usage test

**Comment by zbal** [comment]
Refactoring + new slackbot feature - looks good to me. Merging.

**Pull request merged**
